// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCfdkUv1hTuSqHnoqY-5DIXfF5HEGGZBE',
    appId: '1:257319088130:web:1a3dedcd43c41ef352371b',
    messagingSenderId: '257319088130',
    projectId: 'syncoplan-66',
    authDomain: 'syncoplan-66.firebaseapp.com',
    storageBucket: 'syncoplan-66.appspot.com',
    measurementId: 'G-V2PVZ1NY73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfYzOIvIdwJ__R18Q2-bYgqXs8KZh4ahg',
    appId: '1:257319088130:android:80a2c19128ea157752371b',
    messagingSenderId: '257319088130',
    projectId: 'syncoplan-66',
    storageBucket: 'syncoplan-66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSjngnXCgVVVnA4yCsLYPV-uPa8VYA4u4',
    appId: '1:257319088130:ios:4b420d00cd4efe6752371b',
    messagingSenderId: '257319088130',
    projectId: 'syncoplan-66',
    storageBucket: 'syncoplan-66.appspot.com',
    iosBundleId: 'com.example.syncoplanProject',
  );
}
